module.exports = {



    "baseUrl": "https://docs.gen.vitraclient.ml",
    "colors": "red",
    "copyright": " © 2022 Vitra Development, Inc.",
    "favicon": "favicon.ico",
    "headerIcon": "favicon.ico",

    headerLinks: [
        // Links to document with id doc1 for current language/version
        { doc: "installing", label: "Installing" },
        // Link to page found at pages/en/help.js or if that does not exist, pages/help.js, for current language
        { page: "help", label: "Help" },
        // Links to href destination
        { href: "https://vitraclient.ml", label: "Vitra" },
        // Links to blog generated by Docusaurus (${baseUrl}blog)
 
        // Determines search bar position among links
        { search: true },
        // Determines language drop down position among links
        { languages: true }
      ],

      "tagline": "vitramc",
      "title": "Vitra Project - HeliumGen - Docs",
      "url": "/"

}
